name: app_contatos
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  brasil_fields: ^1.14.0
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  gallery_saver: ^2.3.2
  image_cropper: ^4.0.1
  path_provider: ^2.1.1
  flutter_dotenv: ^5.1.0
  dio: ^5.3.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env
